name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Functions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python modules
      run: |
        python -m pip install coverage
        python -m pip install -r ./web-app/functions/get_reddit_submissions/requirements.txt
    - name: Run coverage
      working-directory: ./web-app/functions/get_reddit_submissions
      run: |
        python -m coverage run -m unittest discover && python -m coverage report --omit "test_*" > coverage.txt
        cov_score=$(awk '$1 == "TOTAL" {print $NF+0}' coverage.txt)
        echo "{ \"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$cov_score\"%, \"color\": \"black\" }" > coverage.json
    - name: Commit changes
      run: |
        git config --global user.name 'Market predictions Coverage Action'
        git config --global user.email 'wrightci01s@gmail.com'
        git add */coverage.json
        git diff-index --quiet HEAD || git commit -m "Auto updating coverage.json"
        git push 
