name: mp-139

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Get changed files
      run: |
        files=`git diff --name-only origin/main origin/${GITHUB_REF##*/}`
        for file in $files; do
          python ./.github/workflows/scripts/custom.py ${file}
        done
        