name: mp-139

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get changed files
      run: |
        git checkout 
        git diff --name-only origin/main ${GITHUB_REF##*/}
