name: Angular Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./web-app
      run: |
        npm ci
        npm run build --if-present
    - name: Test
      working-directory: ./web-app
      run: |
        ng test --sourceMap=false --browsers=ChromeHeadless --watch=false
