name: Regex Annotations

on:
  pull_request:
    branches: [ main ]

jobs:
  RegexAnnotations:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Run regex annotations
      run: |
        files=`git diff --name-only origin/main origin/${GITHUB_HEAD_REF-${GITHUB_REF##*/}}`
        for file in $files; do
          python ./.github/workflows/scripts/regex-annotation.py ${file}
        done
